namespace SdsLib.Domain.Enums;

public enum OrganizationRole
{
    Principal,
    Chair,
    Professor,
    Researcher,
    Adjunct,
    Affiliate,
    OccupationalTherapist,
    PhysicalTherapist,
    SpeechTherapist,
    VisionTherapist,
    Paraprofessional,
    SpecialServices,
    Advisor,
    Proctor,
    Nurse,
    OfficeStaff,
    Lecturer,
    ITAdmin,
    Administrator,
    Teacher,
    Faculty,
    Staff,
    TeacherAssistant,
    Assistant,
    Instructor,
    Substitute,
    Coach,
    Alumni,
    Student,
    Other
}
